FROM yangyangfu/pyomo_ipopt

USER root
RUN pip install casadi
#ENV PATH &PATH:/usr/local/lib/python2.7/dist-packages/casadi
#ENV LD_LIBRARY_PATH $LD_LIBRARY_PATH:/usr/local/lib/python2.7/dist-packages/casadi

USER developer